In [12]:
import numpy as np

# rank 1 array
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

# rank 2 array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
(1, 2, 4)


In [22]:
a = np.zeros((2, 2))
print(a)

b = np.ones((1, 2))
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81169902 0.82374385]
 [0.1437091  0.75191445]]


In [33]:
# Array indexing

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

print(a[:2, 1:3]) # first two subarrays and column 1 & 2
print(a[0, 1])

print('==========')
b = a[:2, 1:3]
print(b)
b[0, 0] = 77
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
[[2 3]
 [6 7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
# slicing

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('=========================')

row_r1 = a[1, :]
print(row_r1, row_r1.shape)

print('==========')

row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)

print('=========================')

col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

print('=========================')


col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(array([5, 6, 7, 8]), (4,))
(array([[5, 6, 7, 8]]), (1, 4))
(array([ 2,  6, 10]), (3,))
(array([[ 2],
       [ 6],
       [10]]), (3, 1))


In [55]:
# integer array indexing
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a)

print(a[[0, 1, 2], [0, 1, 0]]) # (0,0),(1,1),(2,0)
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # similar to above

print(a[[0, 0], [1, 1]]) # (0, 1),(0, 1)
print(np.array([a[0, 1], a[0, 1]]))

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b])

a[np.arange(4), b] += 10 # mutate elements

print(a)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [59]:
# boolean array indexing

a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)

print(a[bool_idx])

print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [65]:
# data types

x = np.array([1, 2])
print(x.dtype)

x = np.array([1, 2.0])
print(x.dtype)

x = np.array([1.0, 2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


In [74]:
# array math

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# all are elements wise operations
print(x + y)
print(np.add(x, y)) # same as above
print("\n")
print(x - y)
print(np.subtract(x, y)) # same as above

print("\n")
print(x * y) # element wise, not matrix multiplication
print(np.multiply(x, y)) # same as above

print("\n")
print(x / y)
print(np.divide(x, y)) # same as above

print("\n")
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[1.         1.41421356]
 [1.73205081 2.        ]]


In [88]:
# dot

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10]) 
w = np.array([11, 12])

print(v)
print(w)
print(x)
print(y)
print(v.dot(w)) # inner product
print(np.dot(v, w))
print(x.dot(v))
print(np.dot(x, v))
print(x.dot(y))
print(np.dot(x,y))

[ 9 10]
[11 12]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [89]:
# sum

x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x)) # sum of all elements
print(np.sum(x, axis=0)) # sum of each column
print(np.sum(x, axis=1)) # sum of each row

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [94]:
# transpose of a matrix
x = np.array([[1,2], [3,4]])
print(x) 

print(x.T)

v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [96]:
# broadcasting

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
print(x)
print(v)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
